import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Providers from "@/contexts/index.contexts";
import localFont from "next/font/local";
import { satoshiFont } from "@/assets/fonts";
export const metadata: Metadata = {
  title: "Snipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased ${satoshiFont.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
