import type { Metadata } from "next";
import "./globals.css";

import { satoshiFont } from "@/assets/fonts";
import Providers from "@/contexts/index.contexts";
export const metadata: Metadata = {
  title: "Snipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased ${satoshiFont.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
